# Generated by Django 5.1.2 on 2025-04-22 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.DecimalField(decimal_places=2, max_digits=10)),
                ('power_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('load_type', models.CharField(choices=[('source', 'Load Source'), ('supply', 'Load Supply')], max_length=10)),
                ('avaliable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
