# Generated by Django 5.1.2 on 2025-05-25 20:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='ACME', max_length=100)),
                ('power', models.DecimalField(decimal_places=2, max_digits=10)),
                ('power_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('load_type', models.CharField(choices=[('source', 'source'), ('supply', 'supply')], max_length=10)),
                ('voltage', models.DecimalField(decimal_places=2, default=110.0, max_digits=10)),
                ('tipo', models.CharField(choices=[('AC', 'AC'), ('DC', 'DC')], default='DC', max_length=2)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('avaliable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
