# Generated by Django 5.1.2 on 2025-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='ACME', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='load_type',
            field=models.CharField(choices=[('source', 'source'), ('supply', 'supply')], max_length=10),
        ),
    ]
