# Generated by Django 5.1.2 on 2025-05-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0002_product_product_name_alter_product_load_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tipo',
            field=models.CharField(choices=[('AC', 'AC'), ('DC', 'DC')], default='DC', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='voltage',
            field=models.DecimalField(decimal_places=2, default=110.0, max_digits=10),
        ),
    ]
