# Generated by Django 5.1.2 on 2025-05-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0003_product_tipo_product_voltage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
