# https://medium.com/@alan-vieira/rodando-mysql-no-docker-e6e05b727196

version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: project-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=project
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --bind-address=0.0.0.0
volumes:
  mysql-volume:
    driver: local